rmdir /q /s target
mkdir target

set "opencover=%UserProfile%\.nuget\packages\opencover\4.7.1221\tools\OpenCover.Console.exe"
set "reportgenerator=%UserProfile%\.nuget\packages\reportgenerator\5.3.5\tools\net8.0\ReportGenerator.exe"
set "xunit=%UserProfile%\.nuget\packages\xunit.runner.console\2.8.1\tools\net48\xunit.console.exe"
set "dotnet=C:\Program Files\dotnet\dotnet.exe"

::%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% .NET 4.7 - OpenCover %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

msbuild .\CoverageDemo.sln /v:m /t:Clean
rmdir /q /s BusinessTest_NetCore\bin
rmdir /q /s BusinessTest_NetCore\obj
msbuild .\CoverageDemo.sln /v:m /t:Restore
msbuild .\CoverageDemo.sln /v:m /t:Rebuild

set "targetdir=target\Net48_OpenCover"
mkdir %targetdir%

"%opencover%" -register:user "-target:%xunit%" -targetargs:"BusinessTest_Net48\bin\Debug\BusinessTest_Net48.dll -noshadow -xml %targetdir%\xunit.xml" -output:%targetdir%\coverage.xml -returntargetcode -coverbytest:* -mergebyhash

"%reportGenerator%" -reports:%targetdir%\coverage.xml -reporttypes:HtmlInline -targetdir:%targetdir% -assemblyfilters:-xunit*

::%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% .NET Core - OpenCover %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

msbuild .\CoverageDemo.sln /v:m /t:Clean
rmdir /q /s BusinessTest_NetCore\bin
rmdir /q /s BusinessTest_NetCore\obj
msbuild .\CoverageDemo.sln /v:m /t:Restore
msbuild .\CoverageDemo.sln /v:m /t:Rebuild

set "targetdir=target\NetCore_OpenCover"
mkdir %targetdir%

"%opencover%" -register:user "-target:%dotnet%" -targetargs:"test BusinessTest_NetCore\BusinessTest_NetCore.csproj" -output:%targetdir%\coverage.xml -returntargetcode -coverbytest:* -mergebyhash -oldstyle

"%reportGenerator%" -reports:%targetdir%\coverage.xml -reporttypes:HtmlInline -targetdir:%targetdir% -assemblyfilters:-xunit*;-AltCover*;-coverlet*;-FSharp.Core*;-Microsoft*;-testhost -classfilters:-AutoGeneratedProgram -riskhotspotassemblyfilters:-Microsoft*;-testhost

::%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% .NET Core - Coverlet - msbuild %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

msbuild .\CoverageDemo.sln /v:m /t:Clean
rmdir /q /s BusinessTest_NetCore\bin
rmdir /q /s BusinessTest_NetCore\obj
msbuild .\CoverageDemo.sln /v:m /t:Restore
msbuild .\CoverageDemo.sln /v:m /t:Rebuild

set "targetdir=target\NetCore_Coverlet_msbuild"
mkdir %targetdir%

"%dotnet%" test --no-build /p:CollectCoverage=true /p:IncludeTestAssembly=true /p:CoverletOutputFormat=\"opencover,cobertura\" /p:CoverletOutput=../%targetdir%/ BusinessTest_NetCore\BusinessTest_NetCore.csproj

"%reportGenerator%" -reports:%targetdir%\coverage.opencover.xml -reporttypes:HtmlInline -targetdir:%targetdir% -assemblyfilters:-xunit* -classfilters:-AutoGeneratedProgram

::%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% .NET Core - Coverlet - collector %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

msbuild .\CoverageDemo.sln /v:m /t:Clean
rmdir /q /s BusinessTest_NetCore\bin
rmdir /q /s BusinessTest_NetCore\obj
rmdir /q /s BusinessTest_NetCore\TestResults
msbuild .\CoverageDemo.sln /v:m /t:Restore
msbuild .\CoverageDemo.sln /v:m /t:Rebuild

set "targetdir=target\NetCore_Coverlet_collector"
mkdir %targetdir%

"%dotnet%" test --no-build --collect:"XPlat Code Coverage" BusinessTest_NetCore\BusinessTest_NetCore.csproj

"%reportGenerator%" -reports:BusinessTest_NetCore\TestResults\*\coverage.cobertura.xml -reporttypes:HtmlInline -targetdir:%targetdir% -assemblyfilters:-xunit* -classfilters:-AutoGeneratedProgram

::%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% .NET Core - AltCover %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

msbuild .\CoverageDemo.sln /v:m /t:Clean
rmdir /q /s BusinessTest_NetCore\bin
rmdir /q /s BusinessTest_NetCore\obj
msbuild .\CoverageDemo.sln /v:m /t:Restore
msbuild .\CoverageDemo.sln /v:m /t:Rebuild

set "targetdir=target\NetCore_AltCover"
mkdir %targetdir%

"%dotnet%" test --no-build /p:AltCover=true /p:AltCoverForce=true /p:AltCoverCallContext=[Fact] /p:AltCoverXmlReport=..\%targetdir%\coverage.opencover.xml /p:AltCoverCobertura=..\%targetdir%\coverage.cobertura.xml BusinessTest_NetCore\BusinessTest_NetCore.csproj

"%reportGenerator%" -reports:%targetdir%\coverage.cobertura.xml -reporttypes:HtmlInline -targetdir:%targetdir% -assemblyfilters:-xunit*;-AltCover*;-Microsoft*;-testhost -classfilters:-AutoGeneratedProgram -riskhotspotassemblyfilters:-Microsoft*;-testhost