rmdir /q /s target
mkdir target

set "opencover=%UserProfile%\.nuget\packages\opencover\4.7.922\tools\OpenCover.Console.exe"
set "reportgenerator=%UserProfile%\.nuget\packages\reportgenerator\4.6.4\tools\netcoreapp3.0\ReportGenerator.exe"
set "xunit=%UserProfile%\.nuget\packages\xunit.runner.console\2.4.1\tools\net452\xunit.console.exe"
set "dotnet=C:\Program Files\dotnet\dotnet.exe"


::%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% .NET 4.7 - OpenCover %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

msbuild .\CoverageDemo.sln /v:m /t:Clean
rmdir /q /s BusinessTest_NetCore3\bin
rmdir /q /s BusinessTest_NetCore3\obj
msbuild .\CoverageDemo.sln /v:m /t:Restore
msbuild .\CoverageDemo.sln /v:m /t:Rebuild

set "targetdir=target\Net47_OpenCover"
mkdir %targetdir%

"%opencover%" -register:user "-target:%xunit%" -targetargs:"BusinessTest_Net47\bin\Debug\BusinessTest_Net47.dll -noshadow -xml %targetdir%\xunit.xml" -output:%targetdir%\coverage.xml -returntargetcode -coverbytest:* -mergebyhash

"%reportGenerator%" -reports:%targetdir%\coverage.xml -reporttypes:HtmlInline -targetdir:%targetdir% -assemblyfilters:-xunit*

::%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% .NET Core 3 - OpenCover %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

msbuild .\CoverageDemo.sln /v:m /t:Clean
rmdir /q /s BusinessTest_NetCore3\bin
rmdir /q /s BusinessTest_NetCore3\obj
msbuild .\CoverageDemo.sln /v:m /t:Restore
msbuild .\CoverageDemo.sln /v:m /t:Rebuild

set "targetdir=target\NetCore3_OpenCover"
mkdir %targetdir%

"%opencover%" -register:user "-target:%dotnet%" -targetargs:"test BusinessTest_NetCore3\BusinessTest_NetCore3.csproj" -output:%targetdir%\coverage.xml -returntargetcode -coverbytest:* -mergebyhash -oldstyle

"%reportGenerator%" -reports:%targetdir%\coverage.xml -reporttypes:HtmlInline -targetdir:%targetdir% -assemblyfilters:-xunit*;-AltCover*;-coverlet* -classfilters:-AutoGeneratedProgram

::%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% .NET Core 3 - Coverlet - msbuild %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

msbuild .\CoverageDemo.sln /v:m /t:Clean
rmdir /q /s BusinessTest_NetCore3\bin
rmdir /q /s BusinessTest_NetCore3\obj
msbuild .\CoverageDemo.sln /v:m /t:Restore
msbuild .\CoverageDemo.sln /v:m /t:Rebuild

set "targetdir=target\NetCore3_Coverlet_msbuild"
mkdir %targetdir%

"%dotnet%" test --no-build /p:CollectCoverage=true /p:IncludeTestAssembly=true /p:CoverletOutputFormat=\"opencover,cobertura\" /p:CoverletOutput=../%targetdir%/ BusinessTest_NetCore3\BusinessTest_NetCore3.csproj

"%reportGenerator%" -reports:%targetdir%\coverage.opencover.xml -reporttypes:HtmlInline -targetdir:%targetdir% -assemblyfilters:-xunit* -classfilters:-AutoGeneratedProgram

::%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% .NET Core 3 - Coverlet - collector %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

msbuild .\CoverageDemo.sln /v:m /t:Clean
rmdir /q /s BusinessTest_NetCore3\bin
rmdir /q /s BusinessTest_NetCore3\obj
rmdir /q /s BusinessTest_NetCore3\TestResults
msbuild .\CoverageDemo.sln /v:m /t:Restore
msbuild .\CoverageDemo.sln /v:m /t:Rebuild

set "targetdir=target\NetCore3_Coverlet_collector"
mkdir %targetdir%

"%dotnet%" test --no-build --collect:"XPlat Code Coverage" BusinessTest_NetCore3\BusinessTest_NetCore3.csproj

"%reportGenerator%" -reports:BusinessTest_NetCore3\TestResults\*\coverage.cobertura.xml -reporttypes:HtmlInline -targetdir:%targetdir% -assemblyfilters:-xunit* -classfilters:-AutoGeneratedProgram

::%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% .NET Core 3 - AltCover %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

msbuild .\CoverageDemo.sln /v:m /t:Clean
rmdir /q /s BusinessTest_NetCore3\bin
rmdir /q /s BusinessTest_NetCore3\obj
msbuild .\CoverageDemo.sln /v:m /t:Restore
msbuild .\CoverageDemo.sln /v:m /t:Rebuild

set "targetdir=target\NetCore3_AltCover"
mkdir %targetdir%

"%dotnet%" test --no-build /p:AltCover=true /p:AltCoverForce=true /p:AltCoverCallContext=[Fact] /p:AltCoverXmlReport=..\%targetdir%\coverage.opencover.xml /p:AltCoverCobertura=..\%targetdir%\coverage.cobertura.xml BusinessTest_NetCore3\BusinessTest_NetCore3.csproj

"%reportGenerator%" -reports:%targetdir%\coverage.opencover.xml -reporttypes:HtmlInline -targetdir:%targetdir% -assemblyfilters:-xunit* -classfilters:-AutoGeneratedProgram